// Incident Triage MCP Handler for Vercel Serverless Functions

function classifySeverity(text) {
  const upper = text.toUpperCase();
  const critical = ["FATAL", "CRITICAL", "SECURITY", "DATA LOSS", "PANIC"];
  const high = ["ERROR", "FAILED", "EXCEPTION", "TIMEOUT", "OUT OF MEMORY"];
  const medium = ["WARN", "WARNING", "DEPRECATED", "RETRY"];

  if (critical.some((k) => upper.includes(k))) return "Critical";
  if (high.some((k) => upper.includes(k))) return "High";
  if (medium.some((k) => upper.includes(k))) return "Medium";
  return "Low";
}

function extractRootCause(lines) {
  const candidates = lines.filter((l) =>
    /error|failed|exception|fatal/i.test(l),
  );
  if (candidates.length === 0) return "No explicit error line found";
  return candidates[0].trim().slice(0, 160);
}

function suggestActions(severity, text) {
  const actions = [];
  const upper = text.toUpperCase();

  if (
    upper.includes("MODULE NOT FOUND") ||
    upper.includes("CANNOT FIND MODULE")
  ) {
    actions.push("Run npm install and verify package-lock.json is committed");
  }
  if (upper.includes("TIMEOUT")) {
    actions.push("Increase CI timeout or split long test suites");
  }
  if (upper.includes("OUT OF MEMORY") || upper.includes("OOM")) {
    actions.push("Increase build runner memory or reduce parallelism");
  }
  if (upper.includes("SECURITY") || upper.includes("VULNERAB")) {
    actions.push("Run npm audit fix and patch vulnerable dependencies");
  }
  if (actions.length === 0) {
    actions.push("Inspect failing step logs and retry with debug output");
  }

  if (severity === "Critical" || severity === "High") {
    actions.push(
      "Notify on-call and consider rollback if impact is production",
    );
  }

  return actions;
}

function buildGitHubIssue(severity, rootCause, logExcerpt) {
  return {
    provider: "github",
    repo: "example-org/example-repo",
    title: `[${severity}] CI Failure: ${rootCause}`,
    body: `Automated incident triage detected a ${severity.toLowerCase()} severity issue:\n\n**Root Cause:** ${rootCause}\n\n**Log Excerpt:**\n\`\`\`\n${logExcerpt}\n\`\`\`\n\nThis issue was automatically generated by Incident Triage Studio powered by Archestra MCP.`,
    labels: [
      severity === "Critical" ? "critical" : "high",
      "automated",
      "incident-triage",
    ],
  };
}

function buildSlackAlert(severity, rootCause) {
  const emoji =
    severity === "Critical"
      ? "🔴"
      : severity === "High"
        ? "🟠"
        : severity === "Medium"
          ? "🟡"
          : "🟢";

  return {
    channel: "#devops-alerts",
    username: "Incident Triage Bot",
    icon_emoji: ":warning:",
    blocks: [
      {
        type: "section",
        text: {
          type: "mrkdwn",
          text: `${emoji} *${severity} Severity Incident*\n_Root Cause:_ ${rootCause}`,
        },
      },
      {
        type: "actions",
        elements: [
          {
            type: "button",
            text: { type: "plain_text", text: "View Details" },
            url: "https://archestra.example.com/incidents",
            style: severity === "Critical" ? "danger" : "primary",
          },
        ],
      },
    ],
  };
}

function triageIncident(logText) {
  const lines = logText.split("\n").filter((l) => l.trim());
  const severity = classifySeverity(logText);
  const rootCause = extractRootCause(lines);
  const actions = suggestActions(severity, logText);

  const logExcerpt = lines.slice(0, 5).join("\n");

  return {
    incidentId: `INC-${Date.now()}`,
    timestamp: new Date().toISOString(),
    severity,
    rootCause,
    suggestedActions: actions,
    githubIssue: buildGitHubIssue(severity, rootCause, logExcerpt),
    slackAlert: buildSlackAlert(severity, rootCause),
    analysisDetails: {
      totalLines: lines.length,
      errorKeywords: lines.filter((l) => /error/i.test(l)).length,
      warningKeywords: lines.filter((l) => /warn/i.test(l)).length,
    },
  };
}

export default function handler(req, res) {
  // Set CORS headers
  res.setHeader("Access-Control-Allow-Credentials", "true");
  res.setHeader("Access-Control-Allow-Origin", "*");
  res.setHeader("Access-Control-Allow-Methods", "GET,OPTIONS,PATCH,DELETE,POST,PUT");
  res.setHeader(
    "Access-Control-Allow-Headers",
    "X-CSRF-Token, X-Requested-With, Accept, Accept-Version, Content-Length, Content-MD5, Content-Type, Date, X-Api-Version"
  );

  if (req.method === "OPTIONS") {
    res.status(200).end();
    return;
  }

  if (req.method === "POST") {
    const { logText } = req.body;

    if (!logText) {
      return res.status(400).json({
        error: "Missing required parameter: logText",
      });
    }

    try {
      const result = triageIncident(logText);
      res.status(200).json(result);
    } catch (error) {
      res.status(500).json({
        error: `Triage failed: ${error.message}`,
      });
    }
  } else {
    res.status(405).json({ error: "Method not allowed" });
  }
}
